version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: mishmarot_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "8245"
      POSTGRES_DB: postgres
    ports:
      - "5435:5432"
    volumes:
      - mishmarot_postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: mishmarot_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  mishmarot_postgres_data:
